# -*- coding: utf-8 -*-
# Generated by https://github.com/i2y/connecpy/protoc-gen-connecpy.  DO NOT EDIT!
# source: haberdasher.proto

from typing import Optional, Protocol, Union

import httpx

from connecpy.async_client import AsyncConnecpyClient
from connecpy.base import Endpoint
from connecpy.server import ConnecpyServer
from connecpy.client import ConnecpyClient
from connecpy.context import ClientContext, ServiceContext
import .i2y.connecpy.example.Hat as _dot_i2y_dot_connecpy_dot_example_dot_Hat
import .i2y.connecpy.example.Size as _dot_i2y_dot_connecpy_dot_example_dot_Size


class Haberdasher(Protocol):
    async def MakeHat(self, req: i2y_dot_connecpy_dot_example.Size, ctx: ServiceContext) -> i2y_dot_connecpy_dot_example.Hat: ...


class HaberdasherServer(ConnecpyServer):
    def __init__(self, *, service: Haberdasher, server_path_prefix=""):
        super().__init__()
        self._prefix = f"{server_path_prefix}/i2y.connecpy.example.Haberdasher"
        self._endpoints = {
            "MakeHat": Endpoint[i2y_dot_connecpy_dot_example.Size, i2y_dot_connecpy_dot_example.Hat](
                service_name="Haberdasher",
                name="MakeHat",
                function=getattr(service, "MakeHat"),
                input=i2y_dot_connecpy_dot_example.Size,
                output=i2y_dot_connecpy_dot_example.Hat,
                allowed_methods=("GET", "POST"),
            ),
        }

    def serviceName(self):
        return "i2y.connecpy.example.Haberdasher"


class HaberdasherSync(Protocol):
    def MakeHat(self, req: i2y_dot_connecpy_dot_example.Size, ctx: ServiceContext) -> i2y_dot_connecpy_dot_example.Hat: ...


class HaberdasherServerSync(ConnecpyServer):
    def __init__(self, *, service: HaberdasherSync, server_path_prefix=""):
        super().__init__()
        self._prefix = f"{server_path_prefix}/i2y.connecpy.example.Haberdasher"
        self._endpoints = {
            "MakeHat": Endpoint[i2y_dot_connecpy_dot_example.Size, i2y_dot_connecpy_dot_example.Hat](
                service_name="Haberdasher",
                name="MakeHat",
                function=getattr(service, "MakeHat"),
                input=i2y_dot_connecpy_dot_example.Size,
                output=i2y_dot_connecpy_dot_example.Hat,
                allowed_methods=("GET", "POST"),
            ),
        }

    def serviceName(self):
        return "i2y.connecpy.example.Haberdasher"


class HaberdasherClient(ConnecpyClient):
    def MakeHat(
        self,
        *,
        request: i2y_dot_connecpy_dot_example.Size,
        ctx: Optional[ClientContext] = None,
        server_path_prefix: str = "",
        use_get: bool = False,
        **kwargs,
    ) -> i2y_dot_connecpy_dot_example.Hat:
        method = "GET" if use_get else "POST"
        return self._make_request(
            url=f"{server_path_prefix}/i2y.connecpy.example.Haberdasher/MakeHat",
            ctx=ctx,
            request=request,
            response_class=i2y_dot_connecpy_dot_example.Hat,
            method=method,
            **kwargs,
        )


class AsyncHaberdasherClient(AsyncConnecpyClient):
    async def MakeHat(
        self,
        *,
        request: i2y_dot_connecpy_dot_example.Size,
        ctx: Optional[ClientContext] = None,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        use_get: bool = False,
        **kwargs,
    ) -> i2y_dot_connecpy_dot_example.Hat:
        method = "GET" if use_get else "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/i2y.connecpy.example.Haberdasher/MakeHat",
            ctx=ctx,
            request=request,
            response_class=i2y_dot_connecpy_dot_example.Hat,
            method=method,
            session=session,
            **kwargs,
        )
