[project]
name = "connecpy"
version = "1.5.0"
description = "Code generator, server library and client library for the Connect Protocol"
authors = [
    { name = "Yasushi Itoh" }
]
requires-python = ">= 3.10"
dependencies = [
    "httpx",
    "protobuf",
]
readme = "README.md"
license-files = ["LICENSE"]

[tool.uv]
dev-dependencies = [
    "asgiref",
    "brotli",
    "example",
    "flask",
    "grpcio",
    "grpcio-tools",
    "pip>=24.0",
    "pyright[nodejs]",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "ruff>=0.9.4",
    "zstandard",
]

[build-system]
requires = ["uv_build>=0.7.21,<0.8.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = [
    "test",
]

[tool.ruff]
# Don't run ruff on generated code from external plugins.
extend-exclude = ["*_pb2.py", "*_pb2.pyi", "*_pb2_grpc.py"]

[tool.pyright]
exclude = [
    # Defaults.
    "**/node_modules",
    "**/__pycache__",
    "**/.*",

    # GRPC python files don't typecheck on their own.
    # See https://github.com/grpc/grpc/issues/39555
    "**/*_pb2_grpc.py",
]

[tool.uv.workspace]
members = [
    "example", 
    "noextras",
]

[tool.uv.sources]
connecpy = { workspace = true }
example = { workspace = true }
