[project]
name = "connecpy"
version = "1.5.0"
description = "Code generator, server library and client library for the Connect Protocol"
authors = [
    { name = "Yasushi Itoh" }
]
dependencies = [
    "httpx",
    "protobuf",
    "zstd-asgi>=0.2",
    "brotli-asgi>=1.4.0",
    "brotli>=1.1.0",
    "zstandard>=0.22.0",
]
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">= 3.9"

[tool.uv]
dev-dependencies = [
    "asgiref",
    "connecpy-example",
    "grpcio",
    "grpcio-tools",
    "pip>=24.0",
    "pyright[nodejs]",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "ruff>=0.9.4",
    "zstd-asgi>=0.2",
]

[build-system]
requires = ["uv_build>=0.7.21,<0.8.0"]
build-backend = "uv_build"

[tool.ruff]
# Don't run ruff on generated code from external plugins.
extend-exclude = ["*_pb2.py", "*_pb2.pyi", "*_pb2_grpc.py"]

[tool.pyright]
exclude = [
    # Defaults.
    "**/node_modules",
    "**/__pycache__",
    "**/.*",

    # GRPC python files don't typecheck on their own.
    # See https://github.com/grpc/grpc/issues/39555
    "**/*_pb2_grpc.py",
]

[tool.uv.workspace]
members = ["example"]

[tool.uv.sources]
connecpy = { workspace = true }
connecpy-example = { workspace = true }
